#! python3

from itertools import count
from itertools import accumulate
"""The sequence of triangle numbers is generated by adding the natural numbers.
What is the value of the first triangle
number to have over five hundred divisors?"""


def sixn():
    """All primes are of the form 6n + 1 or 6n - 1"""
    yield 2
    yield 3
    for i in count(1):
        x = 6 * i + 1
        yield x - 2
        yield x


def n_divisors(n):
    divisors = 1
    limit = int(n / 2 + 1)
    for i in sixn():
        if i > limit:
            break
        x = 0
        while n != 1:
            d, m = divmod(n, i)
            if m:
                break
            else:
                n = d
                x += 1
        else:
            divisors *= (x + 1)
            break
        divisors *= (x + 1)
    return divisors

for i in accumulate(count()):
    if n_divisors(i) > 500:
        print(i)
        break
