#! python3
"""Triangle, pentagonal, and hexagonal numbers are generated by
the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal."""
from itertools import count
from math import sqrt


def is_pentagonal(n):
    return not (1 + sqrt(1 + 24 * n)) % 6


def is_triangular(n):
    return not (-1 + sqrt(1 + 8 * n)) % 2

for i in count(144):
    h = i * (i + i - 1)
    if is_pentagonal(h) and is_triangular(h):
        print(h)
        break
