#! python3
"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised;
what is the value of D?"""
from math import sqrt
from itertools import count
# (3n^2 - n) // 2 = i
# 3//2 n^2 - 1//2 n - i = 0
# 3n^2 - n - 2i = 0
# n = (1 + sqrt(1 + 24 * i)) // 6


def is_pentagonal(n):
    return not (1 + sqrt(1 + 24 * n)) % 6

for i in count(2):
    for j in range(1, i):
        if (is_pentagonal((i * (3 * i - 1) - j * (3 * j - 1)) // 2) and
           is_pentagonal((i * (3 * i - 1) + j * (3 * j - 1)) // 2)):
            print((i * (3 * i - 1) - j * (3 * j - 1)) // 2, i, j)
            break
    else:
        continue
    break
